from .Users import Users
from .Student import Student
from .Camera import Camera
from .Location import Location
from .Detection import Detection
from .DetectionDetails import DetectionDetails
from .Notification import Notification
from .Penalties import Penalty
from .DisciplineCommittee import DisciplineCommittee
from .Guard import Guard
from .CameraLinks import CameraLinks
from .Admin import Admin
